FROM mysql:8.0.33

ENV MYSQL_USER=blog
ENV MYSQL_PASSWORD=a1234
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=ssardb

CMD ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]